### CHAPTER 5:Sequences 

In [2]:
import numpy as np
import pandas as pd

baseline_high = 14.48
highs = np.array([baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684])
highs

array([13.6  , 14.387, 14.585, 15.164])

In [3]:
np.sum(highs)/len(highs)

14.434000000000001

#### 5.1 Arrays

english_parts_of_speech = np.array(["noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection"])
english_parts_of_speech

In [4]:
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684])
highs

array([13.6  , 14.387, 14.585, 15.164])

In [5]:
(9/5) * highs + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

In [6]:
highs.size

4

In [7]:
highs.sum()

57.736000000000004

In [8]:
highs.mean()


14.434000000000001

In [9]:
import numpy as np

In [10]:
np.diff(highs)

array([0.787, 0.198, 0.579])

#### 5.2 Ranges

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [13]:
np.arange(3,30,5)

array([ 3,  8, 13, 18, 23, 28])

In [14]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

In [15]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [16]:
positive_term_denominators=np.arange(1,10000,4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [17]:
positive_terms = 1 / positive_term_denominators

In [18]:
negative_terms = 1 / (positive_term_denominators + 2)

In [19]:
4*(sum(positive_terms)-sum(negative_terms))

3.1413926535917955

#### 5.3 More on Arrays

In [21]:
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684])
highs

array([13.6  , 14.387, 14.585, 15.164])

In [22]:
baseline_low = 3.00
lows = np.array([baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728])
lows

array([2.128, 2.371, 2.874, 3.728])

In [23]:
np.array([
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
])

array([11.472, 12.016, 11.711, 11.436])

In [24]:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

In [25]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [26]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143